name: "Configure Pages"
description: "An action to enable Pages and extract various metadata about a site. It can also be used to configure various static site generators we support as starter workflows."
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  static_site_generator:
    description: "Optional static site generator to attempt to configure (nuxt, next or gatsby)"
    required: false
  token:
    description: "GitHub token"
    default: ${{ github.token }}
    required: true
outputs:
  base_url:
    description: 'GitHub Pages site full base URL. Examples: "https://octocat.github.io/my-repo/", "https://octocat.github.io/", "https://www.example.com/"'
  origin:
    description: 'GitHub Pages site origin. Examples: "https://octocat.github.io", "https://www.example.com"'
  host:
    description: 'GitHub Pages site host. Examples: "octocat.github.io", "www.example.com"'
  base_path:
    description: 'GitHub Pages site full base path. Examples: "/my-repo/" or "/"'
